import {
    resolveAccountArchiveEndpoint,
    resolveAccountDeleteEndpoint,
    resolveAccountEndpoint,
    resolveAccountRestoreEndpoint,
    resolveAccountsInstitutionsEndpoint,
    resolveAccountsEndpoint,
    resolveCardArchiveEndpoint,
    resolveCardDeleteEndpoint,
    resolveCardEndpoint,
    resolveCardRestoreEndpoint,
    resolveCardsAlertsEndpoint,
    resolveCardsEndpoint,
    resolveCardsSummaryEndpoint,
    resolveCategoryEndpoint,
    resolveCategoryReorderEndpoint,
    resolveCategoriesEndpoint,
    resolveCategorySubcategoriesEndpoint,
    resolveFinanceBudgetApplySuggestionsEndpoint,
    resolveFinanceBudgetCopyMonthEndpoint,
    resolveFinanceBudgetEndpoint,
    resolveFinanceBudgetSuggestionsEndpoint,
    resolveFinanceBudgetsEndpoint,
    resolveFinanceGoalContributionEndpoint,
    resolveFinanceGoalEndpoint,
    resolveFinanceGoalsEndpoint,
    resolveFinanceGoalTemplatesEndpoint,
    resolveFinanceInsightsEndpoint,
    resolveFinanceSummaryEndpoint,
    resolveInstitutionsEndpoint,
    resolveSubcategoriesGroupedEndpoint,
    resolveSubcategoryEndpoint,
} from './finance.js';

describe('admin/api/endpoints/finance', () => {
    it('resolve os endpoints v1 de bootstrap financeiro compartilhado', () => {
        expect(resolveInstitutionsEndpoint()).toBe('api/v1/instituicoes');
        expect(resolveAccountsInstitutionsEndpoint()).toBe('api/v1/contas/instituicoes');
        expect(resolveAccountsEndpoint()).toBe('api/v1/contas');
        expect(resolveAccountEndpoint(9)).toBe('api/v1/contas/9');
        expect(resolveAccountArchiveEndpoint(9)).toBe('api/v1/contas/9/archive');
        expect(resolveAccountRestoreEndpoint(9)).toBe('api/v1/contas/9/restore');
        expect(resolveAccountDeleteEndpoint(9)).toBe('api/v1/contas/9/delete');
        expect(resolveCategoriesEndpoint()).toBe('api/v1/categorias');
        expect(resolveCategoryEndpoint(12)).toBe('api/v1/categorias/12');
        expect(resolveCategoryReorderEndpoint()).toBe('api/v1/categorias/reorder');
        expect(resolveCardsEndpoint()).toBe('api/v1/cartoes');
        expect(resolveCardsSummaryEndpoint()).toBe('api/v1/cartoes/resumo');
        expect(resolveCardsAlertsEndpoint()).toBe('api/v1/cartoes/alertas');
        expect(resolveCardEndpoint(4)).toBe('api/v1/cartoes/4');
        expect(resolveCardArchiveEndpoint(4)).toBe('api/v1/cartoes/4/archive');
        expect(resolveCardRestoreEndpoint(4)).toBe('api/v1/cartoes/4/restore');
        expect(resolveCardDeleteEndpoint(4)).toBe('api/v1/cartoes/4/delete');
        expect(resolveFinanceSummaryEndpoint()).toBe('api/v1/financas/resumo');
        expect(resolveFinanceGoalsEndpoint()).toBe('api/v1/financas/metas');
        expect(resolveFinanceGoalEndpoint(42)).toBe('api/v1/financas/metas/42');
        expect(resolveFinanceGoalContributionEndpoint(42)).toBe('api/v1/financas/metas/42/aporte');
        expect(resolveFinanceGoalTemplatesEndpoint()).toBe('api/v1/financas/metas/templates');
        expect(resolveFinanceBudgetsEndpoint()).toBe('api/v1/financas/orcamentos');
        expect(resolveFinanceBudgetEndpoint(7)).toBe('api/v1/financas/orcamentos/7');
        expect(resolveFinanceBudgetSuggestionsEndpoint()).toBe('api/v1/financas/orcamentos/sugestoes');
        expect(resolveFinanceBudgetApplySuggestionsEndpoint()).toBe('api/v1/financas/orcamentos/aplicar-sugestoes');
        expect(resolveFinanceBudgetCopyMonthEndpoint()).toBe('api/v1/financas/orcamentos/copiar-mes');
        expect(resolveFinanceInsightsEndpoint()).toBe('api/v1/financas/insights');
        expect(resolveCategorySubcategoriesEndpoint(12)).toBe('api/v1/categorias/12/subcategorias');
        expect(resolveSubcategoriesGroupedEndpoint()).toBe('api/v1/subcategorias/grouped');
        expect(resolveSubcategoryEndpoint(88)).toBe('api/v1/subcategorias/88');
    });
});